### PR TITLE
WIP: make it build with Rust 1.0.0-alpha

### PR DESCRIPTION
**Pull request by rgs1**
Got half of this working, still need to sort an issue with impl_keyed_iter!

Signed-off-by: Raul Gutierrez S rgs@itevenworks.net

### CODE REVIEW

**Comment by Ryman** [comment]
Looks correct, but can you submit this PR to the [upstream repo](https://github.com/Ryman/groupable-rs) and I can merge it when it's finished?

**Comment by rgs1** [comment]
This is complete now, tests pass. The only big change is that I dropped the impl_keyed_iter macro (it wasn't public anyway) in favor of inlinging it (because the types that need to be passed to K: in the HashMap trait impl). 

Let me know if anything else is needed! Thanks!

**Comment by SimonTeixidor** [comment]
I'm going to merge this, but I'd like you to send the same PR to the upstream repo as @Ryman pointed out. Thanks for your contribution!

**Comment by Ryman** [comment]
@SimonPersson @rgs1 No need to PR upstream, I've pulled it from here.

**Pull request merged**
